# Generated by Django 5.0.1 on 2024-01-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_alter_provider_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Задолженность'),
        ),
    ]
