# Generated by Django 5.0.1 on 2024-01-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_alter_provider_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Задолженность'),
        ),
    ]
