# Generated by Django 5.0.1 on 2024-01-23 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_date_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_release',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 19, 23, 57, 544563, tzinfo=datetime.timezone.utc), verbose_name='Date Released'),
        ),
    ]
