# Generated by Django 5.0.1 on 2024-01-23 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_date_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_release',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Released'),
        ),
    ]
